name: pirmanent_client
description: "Pirmanent desktop client app"
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cryptography: ^2.7.0
  filepicker_windows: ^2.1.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.1.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.1
  path_provider: ^2.1.3
  pocketbase: ^0.18.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdf: ^24.2.9
  syncfusion_flutter_pdfviewer: ^24.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  inno_bundle: ^0.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/branding/
    - assets/icons/
    - assets/documents/


flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/branding/logo_icon.png"

inno_bundle:
  id: 15c3b560-975e-100c-b7d4-4d93b2bc5358
  publisher: Marc Bentoy
  name: pirmanent
  installer_icon: assets/installer_icon.ico