name: pirmanent_client
description: "Pirmanent desktop client app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cryptography: ^2.7.0
  filepicker_windows: ^2.1.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.1
  pocketbase: ^0.18.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdf: ^24.2.9
  syncfusion_flutter_pdfviewer: ^24.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/branding/
    - assets/icons/
    - assets/documents/
